pipeline:
  name: Build MERN-Stack-Example
  identifier: Build_yesh8241_MERN_Stack_Example_1718095267232
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      cd server
                      yarn install;
                      yarn test;
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildPush
                  identifier: BuildPush
                  spec:
                    connectorRef: DockerHarness
                    repo: yeshvanth4u
                    tags:
                      - Latest
                    dockerfile: server/Docerfile
                    context: server
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1718095054081
        repoName: yesh8241/MERN-Stack-Example
        build: <+input>
